name: Sync Docker Images

on:
  schedule:
    - cron: '0 0 * * *'
  
  workflow_dispatch:
  
  push:
    branches:
      - main
    paths:
      - 'sync-config.yaml'
      - 'scripts/**'
      - '.github/workflows/sync-images.yml'

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to target registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.TARGET_REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - name: Sync images
      env:
        TARGET_REGISTRY: ${{ secrets.TARGET_REGISTRY }}
        TARGET_NAMESPACE: ${{ secrets.TARGET_NAMESPACE }}
      run: |
        python scripts/sync.py
    
    - name: Post sync summary
      if: always()
      run: |
        if [ -f sync-results.json ]; then
          echo "## Sync Results" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`json" >> $GITHUB_STEP_SUMMARY
          cat sync-results.json >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        fi